baseURL = 'https://michaeljdennis.com/'
languageCode = 'en-us'
title = 'michaeljdennis'
theme = 'anubis'
googleAnalytics = 'G-BDR8ELQ4L4'

[params]
style = 'dark'

[[params.social]]
id = "github"
name = "michaeljdennis"

[[params.social]]
id = "linkedin"
name = "michaeljdennis"

[[params.social]]
id = "mastodon"
name = "michaeljdennis"
url = "https://mastodon.social/@michaeljdennis"

# [[params.social]]
# id = "twitter"
# name = "michaeljdennis"
# url = "https://twitter.com/michaeljdennis"
